### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by forthrin** [raphnet/vspcplay#1]
It just crashes on startup. How do I fix this? Let me know if you need a crash log. I'm on macOS.

```
vspcplay v1.3
spc buffer size: 1764
sdl audio frag size: 4096
Abort trap: 6
```

**Comment by raphnet** [comment]
What version of macOS? How did you build vspcplay?

I tried compiling it on modern OS X, but I could not compile SDL 1.2 (which vspcplay uses...). I'm tempted to migrate to SDL2..

**Comment by forthrin** [comment]
macOS 10.14.5.

```
$ brew install sdl
$ git clone https://github.com/raphnet/vspcplay
$ make
$ ./vspcplay some.spc
```

Call stack snippet:

```
7   vspcplay                      	0x000000010e689ee0 SDL_main + 1168
8   vspcplay                      	0x000000010e68c060 -[SDLMain applicationDidFinishLaunching:] + 49
```

**Comment by raphnet** [comment]
What version of macOS? How did you build vspcplay?

I tried compiling it on modern OS X, but I could not compile SDL 1.2 (which vspcplay uses...). I'm tempted to migrate to SDL2..

**Comment by raphnet** [comment]
Thanks, using brew was a good idea. I fixed the crash and pushed the fix.

Now music plays, but all I get is a white window. Does it do the same for you?

**Comment by forthrin** [comment]
I also get music with a white window. What I'm most interested in is being able to toggle individual channels with keys (eg. 1-8), and record the enabled channels to a WAV file on disk.

**Comment by leolobato** [comment]
As far as I can tell, this was actually a [bug on SDL 1.2.15](https://discourse.libsdl.org/t/sdl1-macos-mojave-blank-screen-problem/27171) that was fixed on the SDL main repository and is now available on homebrew as version `1.2.15_2`.

So you should just be able to upgrade your homebrew-installed SDL (by using `brew upgrade sdl`) and rebuild vspcplay.

I can confirm it is now working on mac 10.15.6.

![Screen Shot 2020-11-04 at 14 32 22](https://user-images.githubusercontent.com/134285/98117884-a2d3df80-1eaa-11eb-9126-13d829610139.png)

**Comment by forthrin** [comment]
Now works instantly with just "brew install sdl" and "make".

Are there any keystrokes to...

* Toggle voices on/off
* Write audio to .wav file on disk

**Comment by esbeto** [comment]
@forthrin Your best bet is to install Audio Overload it has a feature to toggle the channels.

<img width="817" alt="Screenshot 2020-12-06 at 23 29 36" src="https://user-images.githubusercontent.com/1455236/101294981-02f7d180-381b-11eb-9aa2-3c4ef7d96a37.png">

But to save to wav you will need to record the output of the audio with some other software.

**Comment by raphnet** [comment]
Writing a wave file is now supported (--waveout) and channels can be muted interactively (toggled using the 1-8 keys, and the 0 key toggles mute all / mute none) or from the command-line (with --mute and --unmute).

For instance, to generate a wave from channel 5:
`./vspcplay music/ct-304.spc --nosound --novideo --mute all --unmute 5 --waveout corridor_ch5.wav`

Sorry it took 3 years. Maybe it can still help....

**Comment by forthrin** [comment]
Very nice of you to remember this and add support. This makes it easier for musicians to analyze how the tunes were made.
