### ISSUE TITLE
Not able to compile with MXE.

### ISSUE THREAD

**Issue by ProjectHSI** [raphnet/vspcplay#11]
This project doesn't seem to be able to compile with MXE, as attempting to do so throws compiler errors, as well as command not found messages due to MXEBase bein set incorrectly on certain setup.

Some of these seem to be due to the GCC and G++ builds having slightly different behavior that causes the `#define` lines in main.c to throw compiler errors. "Resolving" these issues doesn't work as it then appears to call undefined functions.

A full log will be provided soon.

**Comment by ProjectHSI** [comment]
These compiler errors are due to inconsistent Makefiles, ignoring the undefined references to waveWriter.

Makefile, non-mxe, has -DVERSION_STR=\"1.5\" in it's arguments to the CXX compiler. Makefile.mxe does not. Fixing this allows main.c to compile.

**Comment by ProjectHSI** [comment]
~~Due to undefined references probably being a missing package, this issue can be resolved by a pull request.~~ Apparently wavewriter.h isn't a package.

**Comment by ProjectHSI** [comment]
Since both of these issues can be fixed by a pull request. No work is needed except for merging the pull request.

**Comment by raphnet** [comment]
You probably just need to add wavewriter.o to the OBJS list in the mxe makefile.
wavewriter.o

Do you intend to submit a pull request? Otherwise I can take care of fixing the MXE build.

**Comment by ProjectHSI** [comment]
Sorry for the late reply. I had to edit and verify it works. I've submitted a pull request now that fixes other problems I spotted with the MXE makefile as well as the one outlined in this document.

**Comment by ProjectHSI** [comment]
https://github.com/raphnet/vspcplay/pull/12

**Comment by ProjectHSI** [comment]
Fixed as #12 was merged.

**Comment by ProjectHSI** [comment]
Also, would you consider releasing the source to VSPCPlay's GUI Frontend? I noticed that that wasn't built when running the MXE makefile.

**Comment by raphnet** [comment]
I would gladly, however I looked a bit and I don't seem to have the source for that frontend. A friend coded this frontend for me, and I do not actually recall ever seeing the source code. As this was nearly 20 years ago, the source is most likely gone.

**Comment by ProjectHSI** [comment]
Unfortunate.

I can live without the frontend though.
