### ISSUE TITLE
Please add option to dump to wav (or pcm at least)

### ISSUE THREAD

**Issue by RiedleroD** [raphnet/vspcplay#2]
would be pretty nice, otherwise I have to do pulseaudio shittery again, like with nosefart (only good nsf player) :(

**Comment by raphnet** [comment]
Yes, this should be possible, but why? Are there no better SPC players out there than this visualization hack? This project is the SPC emulation code from an old version of SNES9x, I'm not sure how accurate it is by today standards...

**Comment by RiedleroD** [comment]
I don't know any better ones, unfortunately. This stuff is really hard to find, especially if you don't want to search through ancient forum boards and download shady DLLs or use badly documented libraries. I still have no idea how to use multidumper on linux 🤦🏻

**Comment by WarrenWilkinson** [comment]
I'm also on Linux, have been looking around, this is the only SPC player I've found that actually works these days :-)

**Comment by WarrenWilkinson** [comment]
Actually, I've just found a better way.  It looks like on Linux a number of media players support SPC files.  Audacious is one, but also gstreamer (if you install the bad plugins: `sudo apt-get install gstreamer1.0-plugins-bad`):

`gst-play-1.0 ../chrono-trigger-music/ct-303.spc`

And to convert it to a wav file:

`gst-launch-1.0 filesrc location=../chrono-trigger-music/ct-303.spc ! decodebin ! audioresample ! audioconvert ! audio/x-raw,format=S24LE,rate=48000 ! wavenc ! filesink location=out.wav`

Huzzah!

**Comment by WarrenWilkinson** [comment]
One more thing, since sound-converter (https://soundconverter.org/) is based on gstreamer, it also benefits from the gstreamer-bad plugins and can convert the audio to whatever format you want.  It even carried forward the tags!

**Comment by raphnet** [comment]
This may be a bit late, but I have finally added wave output. Here is how to convert a single file to .WAV:

`./vspcplay music/ct-304.spc --nosound --novideo --waveout corridor-of-time.wav --status`
