### ISSUE TITLE
This broke for no reason at all???

### ISSUE THREAD

**Issue by ProjectHSI** [raphnet/vspcplay#25]
When I recently tried to run the application, it launched and window was created (along with the user interface working and it's related functions) but the audio didn't start playing. In addition, the virtual APU processor or... whatever it is doesn't progressing, it was just stuck at the default state.

This might've broken with an update to Windows - considering that past builds of the application (tested back to 7c5c1dc6e29e26a72a75677659ee18ec7bee4b01 (past builds were tested with WSL acting as a compatibility layer, not running natively on Windows)) also don't work.

**Comment by raphnet** [comment]
Works fine on Linux here.

Are you sure the .spc file you tried to play has not changed and is still valid and has not been overwritten or something?
vspcplay will load anything random file. For instance, I can do ./vspcplay font.c it starts, but it produces no sound and no APU activity.

**Comment by ProjectHSI** [comment]
Broken SPC file. Whoops.
