### ISSUE TITLE
A few samples skipped at the beginning of playback?

### ISSUE THREAD

**Issue by franciscod** [raphnet/vspcplay#5]
I noticed that when playing Super Mario Kart spc files a few notes at the beginning are missing. This doesn't seem to happen on the same spc files with a different player.

Any clues?

**Comment by raphnet** [comment]
I can try looking into this. Could you share the file or tell me where I can get precisely the same .SPC file this behavior has been observed with?

**Comment by raphnet** [comment]
Commit d1726eba8e92011b9031a692b7096c36917b133f fixes this for me. Can you confirm if it works for you too?

**Comment by franciscod** [comment]
Yes! Thank you!!!
