### ISSUE TITLE
add option to print track durations

### ISSUE THREAD

**Issue by RiedleroD** [raphnet/vspcplay#7]
I'm trying to integrate this into [newdump](https://codeberg.org/Riedler/newdump/), but I need the durations of the tracks for the top-level progress bar before getting all the wav files. If I have time, I'll try opening a PR for this myself, but for now I'll just leave this issue here :)

**Comment by raphnet** [comment]
This information is in the id666 tag. Maybe I should just add a --dump_id6 command-line option which outputs everything and exit?

For instance:
```
$ ./vspcplay ct-121.spc --dump_id6
Filename: ct-121.spc
Title: Kingdom Trial
Game: Chrono Trigger
... (dumper, comment )
time: 3:26 (206s)
```
Would that work for your use case?

**Comment by RiedleroD** [comment]
I'm gonna be honest, I've got no idea what an id666 tag is. As long as the duration is there, I'm happy 😅

I did read a bit about this, but only that there's the duration inside, and that it's optional. I can definitely live with some tracks not having a duration, I already have a fallback for that within newdump.

So, yes, printing id666 tags would be fantastic compared to before!

**Comment by raphnet** [comment]
It's done, I went for --id666 as the command-line argument, and the output is like this:

```$./vspcplay ./music/ct-101.spc
vspcplay v1.4
1 files
File: ./music/ct-101.spc
Title: Presentiment
Game: Chrono Trigger
Dumped by: YK
Comments: Title
Duration (seconds): 32```

**Comment by RiedleroD** [comment]
works. thanks!
