### ISSUE TITLE
plok! playback issue

### ISSUE THREAD

**Issue by RiedleroD** [raphnet/vspcplay#8]
I got the spc files from [here](https://www.zophar.net/music/nintendo-snes-spc/plok) - I assume they're correct, zophar's domain has never failed me so far. They're being played back way too quickly.

I assume Plok! is doing some heavy chip abuse - judging from the absolute banger of a soundtrack - but it'd still be nice if it played back correctly.

I might have time to look into this myself tomorrow, we'll see. I'm completely new to the internals of the SNES though so I doubt I'll find anything 🤷🏻

**Comment by RiedleroD** [comment]
libspc via gst-play seems to play the files back just fine, so this is def. a bug in vspcplay… investigating further

**Comment by raphnet** [comment]
Thanks for confirming that the SPC files from zophar plays fine in a different player, it would have been the first thing I'd try!

As I suspected, this is a problem with the timer implementation. There are 3, and the last timer (timer 2) is supposed to run 8 times faster than timers 0 and 1. https://wiki.superfamicom.org/spc700-reference#timers-194

But for some reason, timer 2 was actually running 4 times faster than it was supposed to, therefore playback was 4x the normal speed. The correct code (labelled "WinSPC") was for some reason disabled using the preprocessor... So this was a very easy fix ;-)

Most games probably only use timer 0 or 1, so I guess this is why this was not noticed!

**Comment by raphnet** [comment]
Commit 947f56721c5a9e189b6eb2046398a5bf651c610a fixes this for me. Could you it does for you as well?

**Comment by RiedleroD** [comment]
yup! this is fixed. Thanks for the quick response!
